import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight, Check, Sparkles } from "lucide-react"
import { SITE_CONFIG } from "@/lib/constants"

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params
  return locale === "en"
    ? { title: "About Andre Almeida | Digital Strategy, Ecommerce & Automation", description: "Learn about Andre Almeida's work across websites, ecommerce, Shopify, automation, AI, SEO/GEO and digital growth." }
    : { title: "Sobre André Almeida | Estratégia Digital, E-commerce e Automação", description: "Conheça o trabalho de André Almeida com websites, e-commerce, Shopify, automação, IA, SEO/GEO, dados e crescimento digital." }
}

export default async function AboutPage({ params }: Props) {
  const { locale } = await params
  const isPt = locale !== "en"
  const lang = isPt ? "pt-BR" : "en"
  const whatsapp = `https://wa.me/${SITE_CONFIG.whatsapp}?text=${encodeURIComponent(isPt ? "Olá André, conheci seu trabalho pelo site e quero conversar sobre meu projeto." : "Hi Andre, I learned about your work through the website and want to discuss my project.")}`
  const principles = isPt
    ? [["01", "Estratégia antes da ferramenta", "A tecnologia muda. O problema comercial precisa estar claro antes da escolha da stack."], ["02", "Design precisa sustentar posição", "Estética sem clareza vira decoração. Cada escolha visual deve reforçar confiança, hierarquia e intenção."], ["03", "Dados precisam virar decisão", "Analytics só tem valor quando ajuda a entender comportamento, atrito e próximos movimentos."], ["04", "Automação precisa simplificar", "Automatizar uma operação confusa só acelera a confusão. Primeiro organizo o fluxo, depois automatizo."]]
    : [["01", "Strategy before tools", "Technology changes. The commercial problem must be clear before choosing the stack."], ["02", "Design should support position", "Aesthetics without clarity become decoration. Visual choices should reinforce trust, hierarchy and intent."], ["03", "Data should become decisions", "Analytics only matters when it helps explain behavior, friction and next moves."], ["04", "Automation should simplify", "Automating a confused operation only accelerates confusion. First organize the flow, then automate it."]]

  return <main className="bg-[#f2efe8] text-[#11110f]">
    <section className="px-5 pb-16 pt-32 sm:px-8 lg:px-10 xl:px-14"><div className="mx-auto grid max-w-[1600px] gap-10 lg:grid-cols-[.53fr_.47fr] lg:items-stretch"><div className="flex flex-col justify-center py-10"><p className="text-[10px] font-semibold tracking-[.2em] text-[#77736b]">{isPt?"SOBRE · ESTRATÉGIA · EXECUÇÃO":"ABOUT · STRATEGY · EXECUTION"}</p><h1 className="mt-8 font-editorial text-[clamp(3.5rem,7vw,7.5rem)] leading-[.88] tracking-[-.05em]">{isPt?"Eu trabalho onde negócio, tecnologia e":"I work where business, technology and"} <span className="italic text-[#5f6559]">{isPt?"percepção se encontram.":"perception meet."}</span></h1><p className="mt-9 max-w-2xl text-base leading-8 text-[#625e56] sm:text-lg">{isPt ? "Meu trabalho não começa com uma plataforma. Começa entendendo o que o negócio vende, quem precisa confiar nele, onde a operação perde força e qual estrutura digital consegue sustentar o próximo estágio." : "My work does not start with a platform. It starts by understanding what the business sells, who needs to trust it, where operations lose strength and what digital structure can support the next stage."}</p><div className="mt-10 flex flex-wrap gap-3"><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-14 items-center gap-3 rounded-full bg-[#11110f] px-7 text-[10px] font-semibold uppercase tracking-[.14em] text-white">{isPt?"Falar comigo":"Talk to me"}<ArrowUpRight className="h-4 w-4"/></a><Link href={`/${lang}/portfolio`} className="inline-flex min-h-14 items-center gap-3 rounded-full border border-[#11110f]/25 px-7 text-[10px] font-semibold uppercase tracking-[.14em]">{isPt?"Ver projetos":"View work"}<ArrowUpRight className="h-4 w-4"/></Link></div></div><div className="relative min-h-[680px] overflow-hidden bg-[#11110f]"><Image src="/images/andre3-small.jpg" alt="André Almeida" fill priority quality={80} className="object-cover object-[center_32%]" sizes="(max-width:1024px) 100vw, 48vw"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-7 text-white sm:p-10"><p className="text-[9px] font-semibold uppercase tracking-[.18em] text-white/45">WEBSITES · COMMERCE · DATA · AI</p><p className="mt-4 max-w-lg font-editorial text-3xl leading-[1] sm:text-4xl">{isPt?"Construir é uma parte. Fazer tudo conversar é o trabalho.":"Building is one part. Making everything work together is the job."}</p></div></div></div></section>

    <section className="border-y border-[#d4cec2] px-5 py-24 sm:px-8 md:py-32 lg:px-10 xl:px-14"><div className="mx-auto max-w-[1500px]"><div className="grid gap-10 lg:grid-cols-[.36fr_.64fr]"><p className="text-[10px] font-semibold tracking-[.2em] text-[#77736b]">{isPt?"01 / POSICIONAMENTO":"01 / POSITION"}</p><div><h2 className="font-editorial text-[clamp(2.8rem,5.5vw,5.8rem)] leading-[.93] tracking-[-.045em]">{isPt?"Não vendo uma única ferramenta.":"I do not sell one tool."} <span className="italic text-[#5f6559]">{isPt?"Construo a combinação certa.":"I build the right combination."}</span></h2><p className="mt-8 max-w-3xl text-base leading-8 text-[#625e56]">{isPt ? "Há projetos em que Shopify é a escolha mais inteligente. Em outros, uma estrutura própria faz mais sentido. Às vezes o gargalo é o site; em outros casos é CRM, tráfego, conteúdo, automação ou a falta de leitura do comportamento do cliente. A solução precisa nascer do diagnóstico, não do produto que alguém quer vender." : "Sometimes Shopify is the smartest choice. In other cases, owned infrastructure makes more sense. The bottleneck may be the website, CRM, acquisition, content, automation or the lack of customer-behavior insight. The solution should come from diagnosis, not from a tool someone wants to sell."}</p></div></div></div></section>

    <section className="px-5 py-24 sm:px-8 md:py-32 lg:px-10 xl:px-14"><div className="mx-auto max-w-[1500px]"><p className="text-[10px] font-semibold tracking-[.2em] text-[#77736b]">{isPt?"02 / PRINCÍPIOS":"02 / PRINCIPLES"}</p><div className="mt-12 grid border-y border-[#d4cec2] md:grid-cols-2">{principles.map(([n,title,text],i)=><article key={n} className={`min-h-72 p-7 sm:p-9 ${i%2===1?"md:border-l md:border-[#d4cec2]":""} ${i>1?"border-t border-[#d4cec2]":""}`}><span className="text-[9px] font-semibold tracking-[.15em] text-[#a08967]">{n}</span><h3 className="mt-10 font-editorial text-3xl sm:text-4xl">{title}</h3><p className="mt-5 max-w-xl text-sm leading-7 text-[#666259]">{text}</p></article>)}</div></div></section>

    <section className="bg-[#11110f] px-5 py-24 text-white sm:px-8 md:py-32 lg:px-10 xl:px-14"><div className="mx-auto max-w-[1500px]"><Sparkles className="h-6 w-6 text-[#c7b18d]"/><div className="mt-8 grid gap-14 lg:grid-cols-[.65fr_.35fr] lg:items-end"><h2 className="font-editorial text-[clamp(3rem,6vw,6.2rem)] leading-[.92] tracking-[-.045em]">{isPt?"O objetivo é que a experiência pareça simples porque":"The goal is for the experience to feel simple because"} <span className="italic text-[#c7b18d]">{isPt?"a complexidade foi resolvida.":"the complexity was resolved."}</span></h2><div><ul className="space-y-3 text-sm text-white/60">{(isPt?["Estratégia e arquitetura","Design e desenvolvimento","E-commerce e conversão","CRM, dados e analytics","SEO/GEO e autoridade","Automação e IA"]:["Strategy and architecture","Design and development","Ecommerce and conversion","CRM, data and analytics","SEO/GEO and authority","Automation and AI"]).map(item=><li key={item} className="flex gap-3"><Check className="h-4 w-4 shrink-0 text-[#c7b18d]"/>{item}</li>)}</ul><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-full bg-[#f2efe8] px-7 text-[10px] font-semibold uppercase tracking-[.14em] text-[#11110f]">{isPt?"Conversar sobre meu projeto":"Discuss my project"}<ArrowUpRight className="h-4 w-4"/></a></div></div></div></section>
  </main>
}
