"use client"

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react"
import { Activity, ArrowUpRight, Clock3, Eye, Flame, Globe2, LogOut, Mail, MapPin, MousePointerClick, RefreshCw, Search, Send, Target, Users } from "lucide-react"

type Overview = { sessions:number; pageviews:number; clicks:number; avg_duration:number; leads:number; conversions:number; conversion_rate:number; emails_scheduled:number; emails_delivered:number; emails_opened:number; emails_clicked:number }
type Session = { id:string; first_seen_at:string; last_seen_at:string; locale?:string; country?:string; region?:string; city?:string; referrer?:string; source?:string; medium?:string; campaign?:string; landing_path?:string; current_path?:string; pages_viewed:number; clicks:number; duration_seconds:number; lead_id?:string; lead_email?:string; lead_name?:string; lead_score?:number; lead_status?:string }
type Event = { id:number; session_id:string; event_type:string; path?:string; element?:string; href?:string; duration_seconds?:number; metadata?:Record<string,unknown>; occurred_at:string }
type Lead = { id:string; email:string; name?:string; phone?:string; company?:string; locale?:string; country?:string; region?:string; city?:string; source?:string; status:string; score:number; consent_email:boolean; created_at:string; last_activity_at:string; converted_at?:string; unsubscribed_at?:string }
type SendRow = { id:string; sequence_index:number; locale:string; resend_email_id?:string; status:string; scheduled_at?:string; sent_at?:string; delivered_at?:string; first_opened_at?:string; first_clicked_at?:string; open_count:number; click_count:number; created_at:string; email:string; name?:string; score:number }
type RankRow = { [key:string]: string | number | null | undefined }
type Snapshot = { overview:Overview; sessions:Session[]; events:Event[]; leads:Lead[]; pages:RankRow[]; click_targets:RankRow[]; sources:RankRow[]; cities:RankRow[]; email_sends:SendRow[] }
type Tab = "overview" | "visitors" | "leads" | "email"

const empty: Snapshot = { overview:{sessions:0,pageviews:0,clicks:0,avg_duration:0,leads:0,conversions:0,conversion_rate:0,emails_scheduled:0,emails_delivered:0,emails_opened:0,emails_clicked:0}, sessions:[],events:[],leads:[],pages:[],click_targets:[],sources:[],cities:[],email_sends:[] }

function fmtSeconds(value=0) { const m=Math.floor(value/60), s=Math.round(value%60); return m ? `${m}m ${s}s` : `${s}s` }
function fmtDate(value?:string) { if(!value)return "—"; return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value)) }
function scoreLabel(score=0) { return score>=60?"QUENTE":score>=30?"MORNO":"FRIO" }
function scoreClass(score=0) { return score>=60?"bg-[#8b3b24] text-white":score>=30?"bg-[#b49970] text-[#11110f]":"bg-[#e5e0d6] text-[#625e56]" }
function pct(part:number,total:number) { return total?Math.round(part*1000/total)/10:0 }

export function DashboardClient() {
  const [password,setPassword]=useState("")
  const [authenticated,setAuthenticated]=useState<boolean|null>(null)
  const [data,setData]=useState<Snapshot>(empty)
  const [days,setDays]=useState(30)
  const [tab,setTab]=useState<Tab>("overview")
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState("")
  const [selectedSession,setSelectedSession]=useState<string>("")
  const [query,setQuery]=useState("")

  const load=useCallback(async()=>{
    setLoading(true); setError("")
    try {
      const r=await fetch(`/api/dashboard?days=${days}`,{cache:"no-store"})
      if(r.status===401){setAuthenticated(false);setData(empty);return}
      if(!r.ok)throw new Error("Falha ao carregar o painel")
      setData(await r.json() as Snapshot);setAuthenticated(true)
    } catch(e){setError(e instanceof Error?e.message:"Erro no painel")} finally{setLoading(false)}
  },[days])

  useEffect(()=>{load()},[load])

  async function login(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"login",password})});if(!r.ok)throw new Error("Senha inválida");setPassword("");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível entrar");setLoading(false)}}
  async function logout(){await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});setAuthenticated(false);setData(empty)}

  const selected=useMemo(()=>data.sessions.find(s=>s.id===selectedSession),[data.sessions,selectedSession])
  const timeline=useMemo(()=>data.events.filter(e=>e.session_id===selectedSession).sort((a,b)=>Date.parse(b.occurred_at)-Date.parse(a.occurred_at)),[data.events,selectedSession])
  const leads=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return data.leads;return data.leads.filter(l=>[l.name,l.email,l.company,l.city,l.source,l.status].some(v=>String(v||"").toLowerCase().includes(q)))},[data.leads,query])
  const emailOpenRate=pct(data.overview.emails_opened,data.overview.emails_delivered)
  const emailClickRate=pct(data.overview.emails_clicked,data.overview.emails_delivered)

  if(authenticated===null || (loading && authenticated!==false)) return <main className="min-h-screen bg-[#11110f] text-[#f2efe8] grid place-items-center p-6"><div className="flex items-center gap-3 text-xs uppercase tracking-[.18em] text-white/60"><RefreshCw className="h-4 w-4 animate-spin"/>Carregando command center</div></main>
  if(authenticated===false) return <main className="min-h-screen bg-[#11110f] px-5 py-12 text-[#f2efe8] sm:px-8"><div className="mx-auto flex min-h-[80svh] max-w-lg items-center"><form onSubmit={login} className="w-full border border-white/15 bg-[#171714] p-6 sm:p-10"><p className="text-[9px] font-semibold uppercase tracking-[.2em] text-[#c7b18d]">PRIVATE COMMAND CENTER</p><h1 className="mt-6 font-editorial text-5xl leading-none tracking-[-.045em] sm:text-6xl">Dados que mostram onde existe intenção.</h1><p className="mt-5 text-sm leading-7 text-white/55">Analytics first-party, CRM, origem, cidade aproximada, comportamento e performance dos e-mails.</p><label className="mt-9 block text-[9px] font-semibold uppercase tracking-[.15em] text-white/45">Senha de acesso<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-3 w-full border-b border-white/25 bg-transparent py-4 text-base normal-case tracking-normal outline-none focus:border-[#c7b18d]"/></label>{error&&<p className="mt-4 text-sm text-[#e5a487]">{error}</p>}<button disabled={loading} className="mt-7 w-full rounded-full bg-[#f2efe8] px-6 py-4 text-[10px] font-bold uppercase tracking-[.15em] text-[#11110f] disabled:opacity-50">{loading?"Entrando...":"Entrar no dashboard"}</button></form></div></main>

  const metrics=[
    ["Visitantes",data.overview.sessions,Users],["Páginas vistas",data.overview.pageviews,Eye],["Cliques",data.overview.clicks,MousePointerClick],["Tempo médio",fmtSeconds(data.overview.avg_duration),Clock3],
    ["Leads",data.overview.leads,Target],["Conversões",data.overview.conversions,Flame],["Taxa de conversão",`${data.overview.conversion_rate||0}%`,Activity],["E-mails clicados",data.overview.emails_clicked,Mail],
  ] as const

  return <main className="min-h-screen bg-[#f2efe8] text-[#11110f]">
    <header className="sticky top-0 z-40 border-b border-[#d4cec2] bg-[#f2efe8]/95 px-4 py-4 backdrop-blur sm:px-7 lg:px-10"><div className="mx-auto flex max-w-[1800px] flex-wrap items-center justify-between gap-4"><div><p className="text-[8px] font-semibold uppercase tracking-[.2em] text-[#a08967]">ANDRÉ ALMEIDA · COMMAND CENTER</p><h1 className="mt-1 font-editorial text-2xl tracking-[-.035em] sm:text-3xl">Dashboard inteligente</h1></div><div className="flex items-center gap-2"><button onClick={load} aria-label="Atualizar" className="grid h-10 w-10 place-items-center rounded-full border border-[#cfc8bc]"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/></button><button onClick={logout} className="inline-flex h-10 items-center gap-2 rounded-full bg-[#11110f] px-4 text-[9px] font-semibold uppercase tracking-[.12em] text-white"><LogOut className="h-3.5 w-3.5"/>Sair</button></div></div></header>

    <div className="mx-auto max-w-[1800px] px-4 py-6 sm:px-7 lg:px-10 lg:py-9">
      <div className="flex flex-col gap-4 border-b border-[#d4cec2] pb-5 md:flex-row md:items-center md:justify-between"><nav className="flex max-w-full gap-1 overflow-x-auto pb-1">{(["overview","visitors","leads","email"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-[9px] font-semibold uppercase tracking-[.13em] ${tab===t?"bg-[#11110f] text-white":"border border-[#cfc8bc]"}`}>{t==="overview"?"Visão geral":t==="visitors"?"Visitantes":t==="leads"?"CRM / Leads":"E-mail marketing"}</button>)}</nav><div className="flex gap-1">{[7,30,90].map(n=><button key={n} onClick={()=>setDays(n)} className={`rounded-full px-3 py-2 text-[9px] font-semibold ${days===n?"bg-[#b49970]":"border border-[#cfc8bc]"}`}>{n}D</button>)}</div></div>
      {error&&<div className="my-5 border border-[#a64b2a]/30 bg-[#a64b2a]/10 p-4 text-sm">{error}</div>}

      {tab==="overview"&&<>
        <section className="grid grid-cols-2 gap-2 py-6 sm:grid-cols-4 lg:gap-3">{metrics.map(([label,value,Icon])=><div key={label} className="min-h-32 border border-[#d4cec2] bg-[#f8f5ef] p-4 sm:p-5"><Icon className="h-4 w-4 text-[#a08967]"/><p className="mt-7 font-editorial text-3xl leading-none sm:text-4xl">{value}</p><p className="mt-2 text-[8px] font-semibold uppercase tracking-[.13em] text-[#77736b]">{label}</p></div>)}</section>
        <section className="grid gap-3 lg:grid-cols-3"><Rank title="Principais origens" icon={<Globe2 className="h-4 w-4"/>} rows={data.sources} labelKey="source" valueKey="sessions"/><Rank title="Cidades" icon={<MapPin className="h-4 w-4"/>} rows={data.cities} labelKey="city" valueKey="sessions"/><Rank title="Páginas mais vistas" icon={<Eye className="h-4 w-4"/>} rows={data.pages} labelKey="path" valueKey="views"/></section>
        <section className="mt-3 grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><div className="border border-[#d4cec2] bg-[#f8f5ef] p-4 sm:p-6"><SectionTitle title="Visitantes recentes" icon={<Users className="h-4 w-4"/>}/><SessionList sessions={data.sessions.slice(0,12)} onSelect={id=>{setSelectedSession(id);setTab("visitors")}}/></div><div className="border border-[#d4cec2] bg-[#11110f] p-5 text-white sm:p-7"><p className="text-[8px] font-semibold uppercase tracking-[.16em] text-[#c7b18d]">E-MAIL INTELLIGENCE</p><h2 className="mt-5 font-editorial text-4xl tracking-[-.04em]">30 PT + 30 EN</h2><div className="mt-8 grid grid-cols-2 gap-px bg-white/10"><MiniMetric label="Agendados" value={data.overview.emails_scheduled}/><MiniMetric label="Entregues" value={data.overview.emails_delivered}/><MiniMetric label="Open rate*" value={`${emailOpenRate}%`}/><MiniMetric label="CTR" value={`${emailClickRate}%`}/></div><p className="mt-5 text-[10px] leading-5 text-white/45">*Aberturas são sinal indicativo; cliques e conversões são métricas mais confiáveis.</p></div></section>
      </>}

      {tab==="visitors"&&<section className="grid gap-4 py-6 xl:grid-cols-[.46fr_.54fr]"><div className="border border-[#d4cec2] bg-[#f8f5ef] p-4 sm:p-6"><SectionTitle title={`Sessões (${data.sessions.length})`} icon={<Users className="h-4 w-4"/>}/><SessionList sessions={data.sessions} selected={selectedSession} onSelect={setSelectedSession}/></div><div className="min-w-0 border border-[#d4cec2] bg-[#f8f5ef] p-4 sm:p-6">{selected?<><div className="flex flex-wrap justify-between gap-4"><div><p className="text-[8px] font-semibold uppercase tracking-[.15em] text-[#77736b]">SESSÃO</p><h2 className="mt-2 font-editorial text-3xl">{selected.lead_name||selected.lead_email||"Visitante anônimo"}</h2></div>{selected.lead_score!=null&&<span className={`h-fit rounded-full px-3 py-2 text-[8px] font-bold tracking-[.12em] ${scoreClass(selected.lead_score)}`}>{scoreLabel(selected.lead_score)} · {selected.lead_score}</span>}</div><div className="mt-6 grid grid-cols-2 gap-px bg-[#d4cec2] sm:grid-cols-4"><Fact label="Cidade" value={[selected.city,selected.region,selected.country].filter(Boolean).join(" · ")||"—"}/><Fact label="Origem" value={selected.source||"direct"}/><Fact label="Páginas" value={String(selected.pages_viewed||0)}/><Fact label="Tempo" value={fmtSeconds(selected.duration_seconds)}/></div><h3 className="mt-8 text-[9px] font-semibold uppercase tracking-[.15em] text-[#77736b]">Timeline</h3><div className="mt-3 max-h-[620px] space-y-2 overflow-y-auto pr-1">{timeline.length?timeline.map(e=><div key={e.id} className="grid grid-cols-[auto_1fr] gap-3 border-l border-[#cfc8bc] py-2 pl-3"><span className="mt-1 h-2 w-2 rounded-full bg-[#b49970]"/><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.1em]">{e.event_type}</p><p className="mt-1 break-words text-xs text-[#625e56]">{e.element||e.path||e.href||"evento"}</p><p className="mt-1 text-[9px] text-[#99938a]">{fmtDate(e.occurred_at)}</p></div></div>):<p className="py-8 text-sm text-[#77736b]">Sem eventos para esta sessão.</p>}</div></>:<div className="grid min-h-72 place-items-center text-center text-sm text-[#77736b]">Selecione uma sessão para ver o percurso completo.</div>}</div></section>}

      {tab==="leads"&&<section className="py-6"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><SectionTitle title={`CRM · ${data.leads.length} leads`} icon={<Target className="h-4 w-4"/>}/><label className="flex min-h-11 items-center gap-2 border border-[#cfc8bc] bg-[#f8f5ef] px-4"><Search className="h-4 w-4 text-[#77736b]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar lead, cidade, empresa..." className="w-full bg-transparent text-sm outline-none sm:w-72"/></label></div><div className="grid gap-2">{leads.map(l=><article key={l.id} className="grid gap-4 border border-[#d4cec2] bg-[#f8f5ef] p-4 md:grid-cols-[1.3fr_.8fr_.65fr_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-editorial text-2xl">{l.name||l.email}</h3><span className={`rounded-full px-2.5 py-1 text-[7px] font-bold tracking-[.12em] ${scoreClass(l.score)}`}>{scoreLabel(l.score)} · {l.score}</span></div><p className="mt-1 truncate text-xs text-[#625e56]">{l.email}{l.company?` · ${l.company}`:""}</p></div><div><p className="text-[8px] uppercase tracking-[.12em] text-[#99938a]">Local / origem</p><p className="mt-1 text-xs">{[l.city,l.country].filter(Boolean).join(" · ")||"—"} · {l.source||"direct"}</p></div><div><p className="text-[8px] uppercase tracking-[.12em] text-[#99938a]">Status</p><p className="mt-1 text-xs font-semibold uppercase">{l.status}</p><p className="mt-1 text-[9px] text-[#77736b]">{l.consent_email?"30 e-mails ativos":"Sem nurture"}</p></div><div className="flex gap-2"><a aria-label="Enviar e-mail" href={`mailto:${l.email}`} className="grid h-10 w-10 place-items-center rounded-full border border-[#cfc8bc]"><Mail className="h-4 w-4"/></a>{l.phone&&<a aria-label="WhatsApp" target="_blank" rel="noopener noreferrer" href={`https://wa.me/${l.phone.replace(/\D/g,"")}`} className="grid h-10 w-10 place-items-center rounded-full bg-[#11110f] text-white"><ArrowUpRight className="h-4 w-4"/></a>}</div></article>)}</div></section>}

      {tab==="email"&&<section className="py-6"><div className="grid gap-2 sm:grid-cols-4"><MetricCompact label="Agendados" value={data.overview.emails_scheduled} icon={<Send className="h-4 w-4"/>}/><MetricCompact label="Entregues" value={data.overview.emails_delivered} icon={<Mail className="h-4 w-4"/>}/><MetricCompact label="Aberturas" value={`${emailOpenRate}%`} icon={<Eye className="h-4 w-4"/>}/><MetricCompact label="Cliques" value={`${emailClickRate}%`} icon={<MousePointerClick className="h-4 w-4"/>}/></div><div className="mt-4 overflow-x-auto border border-[#d4cec2] bg-[#f8f5ef]"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-[#d4cec2] text-[8px] uppercase tracking-[.13em] text-[#77736b]"><th className="p-4">Lead</th><th className="p-4">Seq.</th><th className="p-4">Idioma</th><th className="p-4">Status</th><th className="p-4">Agendado</th><th className="p-4">Aberturas</th><th className="p-4">Cliques</th></tr></thead><tbody>{data.email_sends.map(s=><tr key={s.id} className="border-b border-[#e2dcd1] text-xs"><td className="p-4"><strong>{s.name||s.email}</strong><br/><span className="text-[10px] text-[#77736b]">{s.email}</span></td><td className="p-4">#{String(s.sequence_index).padStart(2,"0")}</td><td className="p-4">{s.locale}</td><td className="p-4"><span className="rounded-full bg-[#e5e0d6] px-2 py-1 text-[8px] font-bold uppercase">{s.status}</span></td><td className="p-4">{fmtDate(s.scheduled_at)}</td><td className="p-4">{s.open_count||0}</td><td className="p-4">{s.click_count||0}</td></tr>)}</tbody></table>{!data.email_sends.length&&<p className="p-8 text-sm text-[#77736b]">Os envios aparecerão aqui assim que um lead autorizar a sequência.</p>}</div></section>}
    </div>
  </main>
}

function SectionTitle({title,icon}:{title:string;icon:React.ReactNode}){return <div className="flex items-center gap-2"><span className="text-[#a08967]">{icon}</span><h2 className="text-[9px] font-bold uppercase tracking-[.15em]">{title}</h2></div>}
function MiniMetric({label,value}:{label:string;value:string|number}){return <div className="bg-[#11110f] p-4"><p className="font-editorial text-3xl">{value}</p><p className="mt-1 text-[8px] uppercase tracking-[.12em] text-white/45">{label}</p></div>}
function MetricCompact({label,value,icon}:{label:string;value:string|number;icon:React.ReactNode}){return <div className="border border-[#d4cec2] bg-[#f8f5ef] p-4"><span className="text-[#a08967]">{icon}</span><p className="mt-5 font-editorial text-3xl">{value}</p><p className="mt-1 text-[8px] uppercase tracking-[.12em] text-[#77736b]">{label}</p></div>}
function Fact({label,value}:{label:string;value:string}){return <div className="min-w-0 bg-[#f2efe8] p-3"><p className="text-[7px] uppercase tracking-[.12em] text-[#99938a]">{label}</p><p className="mt-1 break-words text-xs font-semibold">{value}</p></div>}
function Rank({title,icon,rows,labelKey,valueKey}:{title:string;icon:React.ReactNode;rows:RankRow[];labelKey:string;valueKey:string}){const max=Math.max(1,...rows.map(r=>Number(r[valueKey]||0)));return <div className="border border-[#d4cec2] bg-[#f8f5ef] p-4 sm:p-6"><SectionTitle title={title} icon={icon}/><div className="mt-5 space-y-4">{rows.slice(0,8).map((r,i)=><div key={`${String(r[labelKey])}-${i}`}><div className="flex justify-between gap-3 text-xs"><span className="truncate">{String(r[labelKey]||"—")}</span><strong>{String(r[valueKey]||0)}</strong></div><div className="mt-1 h-1 bg-[#e4ded3]"><div className="h-full bg-[#5f6559]" style={{width:`${Math.max(3,Number(r[valueKey]||0)/max*100)}%`}}/></div></div>)}</div></div>}
function SessionList({sessions,selected,onSelect}:{sessions:Session[];selected?:string;onSelect:(id:string)=>void}){return <div className="mt-4 max-h-[650px] space-y-2 overflow-y-auto">{sessions.map(s=><button key={s.id} onClick={()=>onSelect(s.id)} className={`w-full border p-3 text-left transition ${selected===s.id?"border-[#11110f] bg-[#ebe5da]":"border-[#dfd8cc] bg-[#f8f5ef] hover:border-[#a9a196]"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-semibold">{s.lead_name||s.lead_email||`${s.city||"Visitante"} · ${s.country||""}`}</p><p className="mt-1 truncate text-[9px] text-[#77736b]">{s.source||"direct"} → {s.current_path||s.landing_path||"/"}</p></div><span className="shrink-0 text-[8px] text-[#99938a]">{fmtDate(s.last_seen_at)}</span></div><div className="mt-2 flex gap-3 text-[8px] uppercase tracking-[.09em] text-[#77736b]"><span>{s.pages_viewed||0} páginas</span><span>{s.clicks||0} cliques</span><span>{fmtSeconds(s.duration_seconds)}</span></div></button>)}</div>}
